name: .NET Test Pull Requests

on: 
  workflow_call:
    inputs:
      dotnet-version:
        type: string
        description: 'The version of the .NET SDK to use'
        required: true
        default: '8.0.x'

jobs:
  build:
  
    env:
      BUILD_CONFIG: 'Debug'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['${{inputs.dotnet-version}}']

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration $BUILD_CONFIG
    - name: Test
      run: dotnet test /p:Configuration=$BUILD_CONFIG --no-build --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: TestResults-${{ matrix.dotnet-version }}
      if: ${{ always() }}